# ==============================================================================
# templates/postgres-statefulset.yaml
# ==============================================================================
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels: {{ include "openslides.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels: {{ include "openslides.labels" . | nindent 4 }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "openslides.fullname" . }}-secrets
              key: postgres_password
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        - name: backups
          mountPath: /backups
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "{{ .Values.postgres.user }}"]
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.postgres.storageClass }}
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}
  - metadata:
      name: backups
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ .Values.postgres.storageClass }}
      resources:
        requests:
          storage: 10Gi
{{- end }}

